- hosts: all
  become: yes
  tasks:
    - name: create some user, example 'dhenandi'
      user: name=dhenandi append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'dhenandi' to have less password
      lineinfile:
        dest: /etc/sudoers
        line: 'dhenandi ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=dhenandi key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub