- hosts: master
  become: yes
  tasks:
    - name: initialize master
      shell: sudo kubeadm init --pod-network-cidr=10.244.0.0/16 >> initialized_master.txt
      args:
        chdir: $HOME
        creates: initialized_master.txt

    - name: create kube dir
      become: yes
      become_user: dhenandi
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/dhenandi/.kube/config
        remote_src: yes
        owner: dhenandi

    - name: initialized pod network
      become: yes
      become_user: dhenandi
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml >> initialized_pod_network.txt
      args:
        chdir: $HOME
        creates: initialized_pod_network.txt

    - name: get join command
      shell: sudo kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: node
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt